export interface Client {
  // dCreation: cols[0].ToDate();
  // date_creation: dCreation.Value;
  // date_modification: cols[1].ToDate();
  // id_client: cols[2];
  // nom: cols[3];
  // prenom: cols[4];
  // telephone: cols[5];
  // user_createur: cols[6];
  // salarie: (cols[7]:= "1" ? true : false);
  // code_pin: cols[8].ToStringOrNull();
  // remise_permanente: Conversion.NullableByte(cols[9]);
  // numero_carte: cols[10].FillIn(30);
  // groupe: cols[11].FillIn(15);
  // date_naissance: (cols[12]:= "null" ? null : cols[12].ToDate());
  // email: (cols[13]:= "null" ? null : cols[13]).FillIn(70);
  // code_postal: (cols[14]:= "null" ? null : cols[14]).FillIn(5);
  // axe1: cols[15].FillIn(1);
  // axe2: cols[16].FillIn(1);
  // axe3: cols[17].FillIn(1);
  // axe4: cols[18].FillIn(1);
  // axe5: cols[19].FillIn(1);
  // axe6: cols[20].FillIn(1);
  // axe7: cols[21].FillIn(1);
  // axe8: cols[22].FillIn(1);
  // axe9: cols[23].FillIn(1);
  // axe10: cols[24].FillIn(1);
  // axe11: cols[25].FillIn(1);
  // axe12: cols[26].FillIn(1);
  // axe13: cols[27].FillIn(1);
  // axe14: cols[28].FillIn(1);
  // axe15: cols[29].FillIn(1);
  // axe16: cols[30].FillIn(1);
  // axe17: cols[31].FillIn(1);
  // axe18: cols[32].FillIn(1);
  // axe19: cols[33].FillIn(1);
  // axe20: cols[34].FillIn(1);
  // axe21: cols[35].FillIn(1);
  // axe22: cols[36].FillIn(1);
  // axe23: cols[37].FillIn(1);
  // axe24: cols[38].FillIn(1);
  // axe25: cols[39].FillIn(1);
  // axe26: cols[40].FillIn(1);
  // axe27: cols[41].FillIn(1);
  // axe28: cols[42].FillIn(1);
  // axe29: cols[43].FillIn(1);
  // axe30: cols[44].FillIn(1);
  // message_caisse: null;
  // nom_conjoint: cols[46];
  // prenom_conjoint: cols[47];
  // solde_points: cols[48].ToInt();
  // date_modif_caisse: cols[49].ToDate();
  // date_naissance_enfant1: cols[50].ToDate();
  // date_naissance_enfant2: cols[51].ToDate();
  // date_naissance_enfant3: cols[52].ToDate();
  // date_naissance_enfant4: cols[53].ToDate();
  // sexe_enfant1: cols[54].FillIn(1);
  // sexe_enfant2: cols[55].FillIn(1);
  // sexe_enfant3: cols[56].FillIn(1);
  // sexe_enfant4: cols[57].FillIn(1);
  // sexe: cols[58].FillIn(1);
}

